"""Buyer link API endpoints for signed catalog access."""

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession

from api.schemas.tenant import (
    BuyerLinkListResponse,
    BuyerLinkRequest,
    BuyerLinkResponse,
    ValidateLinkRequest,
    ValidateLinkResponse,
)
from core.config import settings
from core.database import get_db
from core.dependencies import get_current_mayorista
from models.mayorista import Mayorista
from repositories.buyer_link_repo import BuyerLinkRepo
from repositories.tenant_repo import TenantRepo
from services.buyer_link_service import (
    BuyerLinkExpiredError,
    BuyerLinkService,
    InvalidBuyerLinkError,
    InvalidCatalogScopeError,
)
from services.tenant_service import TenantInactiveError, TenantNotFoundError

router = APIRouter(prefix="/api/tenants/buyer-links", tags=["buyer-links"])


def _get_buyer_link_service(
    db: AsyncSession = Depends(get_db),
) -> BuyerLinkService:
    buyer_link_repo = BuyerLinkRepo(db)
    tenant_repo = TenantRepo(db)
    return BuyerLinkService(buyer_link_repo, tenant_repo)


@router.post(
    "",
    response_model=BuyerLinkResponse,
    status_code=status.HTTP_201_CREATED,
)
async def generate_buyer_link(
    body: BuyerLinkRequest,
    mayorista: Mayorista = Depends(get_current_mayorista),
    buyer_link_service: BuyerLinkService = Depends(_get_buyer_link_service),
):
    """Generate a signed catalog access link for buyers."""
    try:
        link, signed_token = await buyer_link_service.generate_link(
            tenant_id=mayorista.tenant_id,
            catalog_ids=body.catalog_ids,
            created_by=mayorista.id,
            ttl_days=body.ttl_days,
        )
    except TenantNotFoundError as exc:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, detail=str(exc)
        ) from exc
    except TenantInactiveError as exc:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, detail=str(exc)
        ) from exc
    except InvalidCatalogScopeError as exc:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST, detail=str(exc)
        ) from exc

    signed_url = f"{settings.FRONTEND_URL}/portal/access?token={signed_token}"

    return BuyerLinkResponse(
        id=link.id,
        tenant_id=link.tenant_id,
        catalog_ids=link.catalog_ids,
        signed_url=signed_url,
        expires_at=link.expires_at,
        created_at=link.created_at,
    )


@router.get("", response_model=BuyerLinkListResponse)
async def list_buyer_links(
    mayorista: Mayorista = Depends(get_current_mayorista),
    buyer_link_service: BuyerLinkService = Depends(_get_buyer_link_service),
):
    """List all buyer links generated by the current tenant."""
    try:
        links = await buyer_link_service.list_links(
            tenant_id=mayorista.tenant_id,
        )
    except TenantNotFoundError as exc:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, detail=str(exc)
        ) from exc

    return BuyerLinkListResponse(links=links)


# Public endpoint (no auth required)
validate_router = APIRouter(tags=["buyer-links-public"])


@validate_router.post(
    "/api/buyer-links/validate",
    response_model=ValidateLinkResponse,
)
async def validate_buyer_link(
    body: ValidateLinkRequest,
    buyer_link_service: BuyerLinkService = Depends(
        lambda db: _get_buyer_link_service(db)
    ),
    db: AsyncSession = Depends(get_db),
):
    """Validate a buyer link token and return accessible catalog IDs."""
    try:
        service = _get_buyer_link_service(db)
        result = service.validate_link(body.token)

        return ValidateLinkResponse(
            valid=True,
            tenant_id=result["tenant_id"],
            catalog_ids=result["catalog_ids"],
        )
    except BuyerLinkExpiredError as exc:
        return ValidateLinkResponse(
            valid=False,
            error=str(exc),
        )
    except InvalidBuyerLinkError as exc:
        return ValidateLinkResponse(
            valid=False,
            error=str(exc),
        )
