apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: virtual-closet-staging
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: virtual-closet-staging
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: celery-worker
  namespace: virtual-closet-staging
